#THS IS THE PRINCIPAL FILE ON DIRETORY, IT WILL RUN YOUR SITE, WIHOUT THAT THE SITE.
# WILL SHOW ERROR.
# PLEASE, DON'T DELETE ANY VARIABLE IN THIS FILE.
# IN CASE OF THE DEVELOPMENT USE THE _config-dev.yml FILE.

title: RAINCORN # Title of the site.
lead: We work to do the purposes of the web. # Subtitle or site slogan.
ministry: Alipseight  # Owner of the site.
maintained: Core team # Person or team that maintain the repository
email: raincorn@gmail.com # Email
url: "https://raincorn.github.io" # site URL
repo: "https://github.com/raincorn/raincorn.github.io" # Site repository on Github

# SITE CONFIG

currently_version: 0.0.0 # Current version
currently_release: 0.0.0-rls # Current release
markdown: kramdown # Text type (Github Markdown)
